[MIG][9.0] medical prescription us
OCA/vertical-medical pull request #150
Opened 2016-12-30 15:31 UTC by bmw95

This module extends medical prescription with US Locale logic.

@lasley ping

2016-12-30 19:00 UTC, lasley commented
@bmw95 - When making dependent PRs, you need to note them in your original comment. I have done that for you, but please heed this advice for future.

2017-01-04 02:42 UTC, jcdrubay commented
The code looks great.

I would add few short lines in the README to list the local specifics coped by each of the module, ideally with a link that presents the legal requirement.

2017-01-18 17:59 UTC, bmw95 commented
@jcdrubay apologies for the late reply. Thank you for your comments :) I updated the readme to be more descriptive of the module. There doesn't seem like a whole lot to mention, so I just kept it short and sweet.

ready for review!

2017-01-19 12:02 UTC, jcdrubay commented
Nice! Maybe the new fields `refill_qty_original` and `refill_qty_remain` should be part of `medical_prescription`. Should we add it to the Roadmap?

2017-01-19 17:03 UTC, lasley commented
@jcdrubay - They used to be a part of medical_prescription. I was told by a few people, French mainly, that the concept of a prescription refill is not universal. This was confirmed by @bmw95, who is in Canada & noted the same thing.

Does Vietnam have Rx refills? We may just want to look into some more generic naming or something?

2017-01-21 02:12 UTC, lasley requested changes

2017-01-21 02:12 UTC, lasley commented on medical_prescription_us/models/medical_prescription_order_line.py
> +# @TODO: Abstract control codes into core, add months till expire
Move this to roadmap. Link to RFC https://github.com/OCA/product-attribute/issues/225

2017-01-21 02:12 UTC, lasley commented on medical_prescription_us/models/medical_prescription_order_line.py
> +                pass
Move date_start and medicament declarations outside of the try/except. Add here:
```
_logger.info('%s is not a valid control code (%s)', medicament.control_code, medicament)
```

2017-01-23 20:25 UTC, bmw95 commented on medical_prescription_us/models/medical_prescription_order_line.py
> +                pass
@lasley date_start_treatment is not a required field so this will cause issues when calculating date_stop_treatment.

2017-01-23 20:35 UTC, lasley commented on medical_prescription_us/models/medical_prescription_order_line.py
> +                pass
What specific issues are being circumvented by keeping everything in the try/except?

The issues you are referring to exist regardless, and are fixed in 067e0656c563548064f8cc65ae121f69bbf9950c - I will be submitting an OCA patch later today.

2017-01-23 23:29 UTC, bmw95 commented
@lasley well this is a bit odd. In terms of the date_start_treatment, I tried a bunch of different configs with the demo data and found the following: (model logic is updated in pr)

* **No date_start_treatment defined in rx_line but in related medication** => **Install Error**
    * When I disable the model logic for def create, the form shows that the date_start_treatment field is populated in the rx_line, so it is properly inheriting the field from its related medication
* **date_start_treatment explicitly defined in rx_line** => Installs fine, however creating a new rx_line without date_start_treatment gives **Creation Error**. Your upcoming pr will fix that though.
* Date of 1983-01-20 in demo turns out as 01/19/1983 16:00:00 in frontend form, however if selected in form on creation, the date is correct. Could be my bad in the demo.

### Install Error
* Happens when installing module
````
  File "/media/sf_odoo9dev/vertical-medical/medical_prescription_us/models/medical_prescription_order_line.py", line 50, in create
    vals['date_start_treatment']
ParseError: "date_start_treatment" while parsing /media/sf_odoo9dev/vertical-medical/medical_prescription_us/demo/medical_prescription_order_line_demo.xml:7, near
<record id="medical_prescription_order_order_line_us_1" model="medical.prescription.order.line">
        <field name="prescription_order_id" ref="medical_prescription_us.medical_prescription_prescription_order_us_1"/>
        <field name="medical_medication_id" ref="medical_prescription_us.medical_patient_medication_medication_us_1"/>
        <field name="is_substitutable">True</field>
        <field name="qty">2920</field>
        <field name="medicament_id" ref="medical_prescription_us.medical_medicament_pravastatin_us_1"/>
    </record>
````

### Creation Error
* Added date_start_treatment to rx_line to bypass Install Error
* This error happens when creating rx_line in form view without date_start_treatment defined
* **Just checked while writing, this does not happen when you specify a date_start_treatment in the form, and creation works, so your upcoming PR will fix that**
````
  File "/media/sf_odoo9dev/vertical-medical/medical_prescription_us/models/medical_prescription_order_line.py", line 61, in create
    date_start + delta
  File "/var/www/odoo/_venv/local/lib/python2.7/site-packages/dateutil/relativedelta.py", line 318, in __radd__
    return self.__add__(other)
  File "/var/www/odoo/_venv/local/lib/python2.7/site-packages/dateutil/relativedelta.py", line 276, in __add__
    raise TypeError("unsupported type for add operation")
TypeError: unsupported type for add operation
````

2017-02-13 22:12 UTC, bmw95 commented on medical_prescription_us/models/medical_prescription_order_line.py
> +            date_start = fields.Datetime.from_string(
@lasley The changes requested to move date_start and medicament outside of the `try` block is causing several issues it seems, as described in the previous comment. Is it okay if we defer these changes until 10.0 and move to the roadmap instead here?

2017-02-15 19:40 UTC, bmw95 commented
Refactors to rx_line create method are deferred to laslabs/vertical-medical#166.

Ready to go.

2017-02-17 17:49 UTC, lasley approved these changes

2017-02-17 17:50 UTC, lasley commented
@tedsalmon please review

2017-02-21 17:06 UTC, tedsalmon approved these changes
Minor issues found. Otherwise, LGTM! 👍

2017-02-21 17:06 UTC, tedsalmon commented on medical_prescription_us/README.rst
> +help us smashing it by providing a detailed and welcomed feedback.
Not using the newest verbiage ;)

2017-02-21 17:06 UTC, tedsalmon commented on medical_prescription_us/models/medical_prescription_order_line.py
> +from openerp import api, fields, models, _
IIRC, `_` should be first in the import list.

2017-02-21 17:06 UTC, tedsalmon commented on medical_prescription_us/views/medical_prescription_order_line_view.xml
> +<?xml version="1.0" encoding="utf-8"?>
This entire file seems to be using tabs and not space :(

2017-02-21 19:03 UTC, bmw95 commented
@tedsalmon thanks! Fixed.

2017-03-02 16:53 UTC, merged