[MIG] medical_base_us: Migrate to 10.0
OCA/vertical-medical pull request #156
Opened 2017-01-11 16:09 UTC by kellylougheed

2017-01-11 16:23 UTC, lasley commented on medical_base_us/__manifest__.py
> +        'medical',
This is how you can tell what your PR depends on

2017-01-14 19:58 UTC, lasley commented
Rebased now that depend has been merged

2017-01-14 20:09 UTC, lasley approved these changes
LGTM thanks @kellylougheed

2017-01-14 20:10 UTC, lasley requested changes
Oops just looked at the commit message, looks like some other stuff got squashed in the description. Please amend the commit to fix the message

We're also missing some history. Best way to get it back is to
* check this branch out, 
* reset --hard to OCA/10.0, 
* run the format-patch from OCA/10.0..OCA/9.0 (to get our lost history),
* then cherry pick the b03ab16d6efd63857b9012679f2dd33f9ca7bb40 commit from here choosing to prefer their's (the cherry picked) over your's (9.0 filtered), 
* then fix the message

2017-01-26 02:59 UTC, lasley commented
@kellylougheed - is this ready for review?

2017-01-26 05:20 UTC, kellylougheed commented
@lasley yes!

2017-01-26 17:32 UTC, lasley commented
@kellylougheed - https://github.com/OCA/vertical-medical/pull/156#pullrequestreview-16701357 is still unattended to

2017-01-26 21:30 UTC, kellylougheed commented
Whoops, I thought I had done that! Just went through all the steps in your review @lasley

2017-02-14 23:40 UTC, lasley requested changes

2017-02-14 23:40 UTC, lasley commented on medical_base_us/README.rst
> +* Dave Lasley <dave@laslabs.com>
Add yourself

2017-02-14 23:40 UTC, lasley commented on medical_base_us/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Please update this to the new ReadMe template https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2017-02-14 23:40 UTC, lasley commented on medical_base_us/__openerp__.py
> +# -*- coding: utf-8 -*-
Remove this file

2017-02-14 23:40 UTC, lasley commented on medical_base_us/models/medical_abstract_dea.py
> +from odoo import models, api
Alphabetize imports

2017-02-14 23:40 UTC, lasley commented on medical_base_us/models/medical_abstract_dea.py
> +import re
stdlib packages should be imported above odoo packages. Import ordering - https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#imports

2017-02-14 23:40 UTC, lasley commented on medical_base_us/models/medical_abstract_dea.py
> +        if len(dea_num) != 9:
`len(str(dea_num))`

2017-02-15 17:43 UTC, kellylougheed commented
Changes made @lasley

2017-11-22 02:39 UTC, obulkin commented
This PR has been superseded by https://github.com/OCA/vertical-medical/pull/196 and can be closed.

2017-11-22 18:12 UTC, closed without merging