[10.0][IMP] Isolate medical.procedure
OCA/vertical-medical pull request #181
Opened 2017-07-27 21:51 UTC by obulkin

[IMP] ``medical_emr``: Isolate ``medical.procedure``
* Move ``medical.procedure`` model, views, actions, menu item, and security rules into separate module ``medical_procedure``
* Update manifest accordingly, adding a ``medical_procedure`` dependency

[ADD] ``medical_procedure``: Isolate ``medical.procedure``
* Move ``medical.procedure`` model, views, actions, menu item, and security rules from ``medical_emr``
* Update code to use v10 syntax and align better with OCA guidelines
* Make minor enhancements to model and views

2017-07-27 21:51 UTC, lasley commented
cc @jbeficent

2017-07-29 17:09 UTC, lasley requested changes
Thanks @obulkin - procedure looks good. Just need to revert some adds in emr - explanation inline

2017-07-29 17:09 UTC, lasley commented on medical_emr/__manifest__.py
> +    'depends': [
`medical_emr` is a deprecated module & is being stripped for parts. As such, the only changes that we should see in this module is the removal of logic that is being used elsewhere. We should not be adding anything.

2017-07-29 17:11 UTC, lasley commented
It's worth noting that this is precursor to implementation of the full [FHIR Procedure](https://www.hl7.org/fhir/procedure.html) spec

2017-07-29 17:31 UTC, jbeficent commented
Perhaps we can find a common definition with our current WIP:

https://github.com/Eficent/vertical-medical/blob/10.0-
feature-procedurerequest/medical_procedure/README.rst

We're happy to discuss

Cc @rgarnau


On Jul 29, 2017 7:11 PM, "Dave Lasley" <notifications@github.com> wrote:

> It's worth noting that this is precursor to implementation of the full FHIR
> Procedure <https://www.hl7.org/fhir/procedure.html> spec
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/vertical-medical/pull/181#issuecomment-318844756>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHU_VpcPqa-56OIZeJE09V4xspcefBSKks5sS2emgaJpZM4Ol4nV>
> .
>

2017-07-29 18:06 UTC, lasley commented
Your version looks more complete to me IMO, we should probably just go with that. Looks like you've implemented into stuff already, and we haven't yet. 

Are you anywhere near ready for a PR on your side?

2017-07-29 19:37 UTC, jbeficent commented
Yes, we are planning to use intensively. We are integrating it with Care
Plans
https://github.com/Eficent/vertical-medical/tree/10.0-feature-careplan?files=1

There's plenty of stuff that we want to propose to OCA. We we've been in
experimentation mode for a while, but perhaps it is best to propose the
work now.

So far we have implemented, the following from FHIR (not strictly, though):
- Encounter
- Care Plan
- Request Group
- Procedure Request
- Procedure
- Workflow - Plan definition

The area that seems most complex is the integration with billing, and we
are not using Claims.

On Jul 29, 2017 8:06 PM, "Dave Lasley" <notifications@github.com> wrote:

> Your version looks more complete to me IMO, we should probably just go
> with that. Looks like you've implemented into stuff already, and we haven't
> yet.
>
> Are you anywhere near ready for a PR on your side?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/vertical-medical/pull/181#issuecomment-318848099>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHU_VmRqCaMfHwlTKizk4Z9dWSLPFKAHks5sS3ShgaJpZM4Ol4nV>
> .
>

2017-07-29 19:56 UTC, lasley commented
Awesome, thanks Jordi! We were about to use Procedures in the upgrade of `medical_lab`, which I believe is being formed into the [DiagnosticReport](https://www.hl7.org/fhir/diagnosticreport.html) (@obulkin correct me if I'm wrong).

Now that we have two of us working pretty heavily in this, we're diverging pretty hard. Do you think it would be beneficial to move into an OCA incubator instead of our forks? I've teased with the idea previously, but it never seemed beneficial until now.

Regarding billing - yeah that's a can of worms, even without claims. At this point in pharma, we've pretty much just been integrating billing into Odoo as much as possible - but we've been hitting a lot of walls with it, and it's a cash-only thing. 

Are you having to consider for insurances?

2017-07-31 21:42 UTC, obulkin commented
@jbeficent - It's good to see that someone else is working on this and also trying to align with the FHIR spec. My goal here was just to represent the reusable [CodeableConcept](https://www.hl7.org/fhir/datatypes.html#CodeableConcept) portion of a procedure, the actual service that's being requested in a [ProcedureRequest](https://www.hl7.org/fhir/procedurerequest.html). Here are some examples: https://www.hl7.org/fhir/valueset-procedure-code.html. 

It looks like you've decided to handle that using the product model, which is probably a good move because of all the useful logic that already exists in Odoo for products. Let me know if that's an accurate assessment of your code as it means we can close this PR and further refactor ``medical_lab`` to use your ``medical.procedure.request`` model in place of a roughly equivalent ``medical.diagnostic.request`` model that I was planning to introduce there.

2017-08-14 20:11 UTC, lasley commented
Closing this

2017-11-22 20:31 UTC, obulkin commented
My understanding is that #186 has been dropped in favor of v11 development, so this PR is once again needed for bringing ``medical_diagnostic`` (formerly ``medical_lab``) to v10.

2017-11-23 03:10 UTC, obulkin commented
``medical_emr`` has been removed from the repo due to copyright concerns, so I've refactored ``medical_procedure`` to eliminate any non-trivial use of ``medical_emr`` code. It should now be ready for a new round of review.

2017-11-27 22:35 UTC, lasley approved these changes
Thanks @obulkin

2017-12-13 17:36 UTC, merged