[10.0][ADD] medical_pathology_import: Import interface
OCA/vertical-medical pull request #192
Opened 2017-08-11 02:31 UTC by obulkin

[ADD] ``medical_pathology_import``: Import interface
* Add wizard that provides UI for importing external pathology data. The wizard methods effectively define an interface that must be extended to support specific import use cases

This PR is a continuation of https://github.com/OCA/vertical-medical/pull/140, which was closed in favor of a v10 submission.

Depends on:
- [ ] https://github.com/OCA/vertical-medical/pull/190

2017-11-20 22:43 UTC, lasley requested changes
Thanks @obulkin - few minor changes

2017-11-20 22:43 UTC, lasley commented on medical_pathology_import/wizards/medical_pathology_import.py
> +        record.do_import()
Let's add a context key to skip this. `no_import=True`

Never know when you need to skip a long operation when coding.

2017-11-20 22:43 UTC, lasley commented on medical_pathology_import/wizards/medical_pathology_import.py
> +            name: (str) Name of pathology to create.
Ewww I did these wrong. Can you please fix? Format is:

```
variable name (type): Description
```

2017-11-20 22:43 UTC, lasley commented on medical_pathology_import/wizards/medical_pathology_import.py
> +            category: (medical.pathology.category) Singleton representing the
Models should be the actual name and not the `_name`. So `MedicalPathologyCategory`

2017-11-20 22:43 UTC, lasley commented on medical_pathology_import/wizards/medical_pathology_import.py
> +            (medical.pathology) Newly created Pathology.
`type: Description`

2017-11-21 02:51 UTC, obulkin commented
@lasley - I've pushed up a commit that should address your comments.

2017-11-21 16:17 UTC, lasley approved these changes

2017-11-21 16:47 UTC, merged

2017-11-21 16:47 UTC, lasley commented
Merging - there are no other reviewers for this branch