Feature/9.0 medical prescription sale
OCA/vertical-medical pull request #83
Opened 2016-02-04 06:15 UTC by lasley

This is dependent on #79 and #53 

This module adds a wizard to create quotations from prescription lines.

2016-02-04 07:23 UTC, JonathanNEMRY commented on medical/models/medical_patient.py
> +    def action_invalidate(self, ):
remove comma

2016-02-04 07:23 UTC, JonathanNEMRY commented on medical/models/medical_patient.py
> +    def create(self, vals, ):
remove comma

2016-02-04 07:29 UTC, JonathanNEMRY commented on medical_pathology/__init__.py
> +#    Author: Dave Lasley <dave@laslabs.com>
Use the correct OCA header like https://github.com/OCA/maintainer-tools/blob/master/template/module/exceptions.py#L2

2016-02-04 07:32 UTC, JonathanNEMRY commented on medical_pathology/tests/__init__.py
> +#    This program is free software: you can redistribute it and/or modify
same comment for the header

2016-02-04 09:00 UTC, lasley commented on medical_pathology/tests/__init__.py
> +#    This program is free software: you can redistribute it and/or modify
Thanks @JonathanNEMRY - Will apply this to all PRs, and rebase accordingly

2016-12-09 23:46 UTC, lasley commented
Note this migration should also include https://github.com/laslabs/vertical-medical/pull/52

2016-12-20 16:01 UTC, bmw95 commented
This is ready, minus lint check fails and rebase after prescription thread is merged

2016-12-20 17:07 UTC, lasley commented
Rebased now that #141 is merged

2016-12-20 17:12 UTC, bmw95 commented
lol dang was just doing that xD. Will fix the lint errors.

2016-12-22 13:14 UTC, woodbrettm reviewed
This points out a few notable changes. Thing or two needs to be fixed.

2016-12-22 13:14 UTC, bmw95 commented on sale_medical_prescription/wizards/medical_sale_wizard.py
> +            # if self.split_orders == 'patient':
Remove these comments, as well as those on 89 and 90. Already in readme.

2016-12-22 13:14 UTC, bmw95 commented on sale_medical_prescription/wizards/medical_sale_wizard.py
> -                'partner_invoice_id': patient_id.id,
@lasley these were changed from `patient_id.id` to `partner_id.id`. During testing I had initially tested against patients, however the tests showed the results were pointing to related partner of patient.

2016-12-22 13:14 UTC, bmw95 commented on sale_medical_prescription/wizards/medical_sale_temp.py
> +            #  @TODO
Remove comments. @lasley do we need `payment_term` and `fiscal_position`? If so, should I put it in the roadmap?

2016-12-22 13:14 UTC, bmw95 commented on sale_medical_prescription/README.rst
> +When viewing a prescription order line, click on `Action` in the top middle of the view and choose `Create Quote(s)`.
@lasley the readme has not been updated yet to reflect your opened issue #147

2016-12-22 13:14 UTC, bmw95 commented on sale_medical_prescription/models/medical_medicament.py
> -            if not rec_id.categ_id:
`categ_id` is a required field AFAIK so removed this check. @lasley pointing out in case you want me to keep it.

2016-12-22 13:18 UTC, bmw95 commented
ah woops looks like I may have commented on my first commit hence the collapsed comments. All are still relevant, however. Ready for review!

2016-12-22 13:30 UTC, bmw95 commented on sale_medical_prescription/wizards/medical_sale_temp.py
> +            #  @TODO
was getting warnings that those fields don't exist in sale.order

2016-12-23 01:56 UTC, bmw95 commented on sale_medical_prescription/__openerp__.py
> +        "views/medical_sale_wizard_view.xml",
As per oca template, wizard views should be moved back to wizards folder

2016-12-25 13:40 UTC, bmw95 commented on sale_medical_prescription/demo/medical_medicament_demo.xml
> +        <field name="type">consu</field>
medicaments should all be product

2016-12-27 01:29 UTC, lasley commented on sale_medical_prescription/demo/medical_medicament_demo.xml
> +        <field name="type">consu</field>
This is incorrect; product is a stock dependency. Leave as is

2016-12-27 01:37 UTC, lasley reviewed
Thanks @bmw95 - comments inline

@t3ddftw please review

2016-12-27 01:37 UTC, lasley commented on sale_medical_prescription/README.rst
> +When viewing a prescription order line, click on `Action` in the top middle of the view and choose `Create Quote(s)`.
In this case, we're actually fine. The only concept added is documented

2016-12-27 01:37 UTC, lasley commented on sale_medical_prescription/models/medical_patient.py
> +    # @TODO: Get rid of these in favor of relations. Quick fix for website
Move this to roadmap

2016-12-27 01:37 UTC, lasley commented on sale_medical_prescription/models/medical_pharmacy.py
> +    def _compute_verified_by_id(self):
`_compute_verified_by_id_and_date`

2016-12-27 01:37 UTC, lasley commented on sale_medical_prescription/models/medical_physician.py
> +    def _compute_verified_by_id(self):
_compute_verified_by_id_and_date

2016-12-27 01:37 UTC, lasley commented on sale_medical_prescription/models/medical_physician.py
> +    is_verified = fields.Boolean(
Add to readme:
`* Move duplicated `is_verified`, `verified_by_id`, `verified_date` & related methods to `medical.entity.abstract`

2016-12-27 01:37 UTC, lasley commented on sale_medical_prescription/models/medical_pharmacy.py
> +        for rec_id in self:
Do a string replace in this module to switch all the `rec_id` to `record`

2016-12-27 01:37 UTC, lasley commented on sale_medical_prescription/models/sale_order.py
> +            prescription_ids = []
`prescriptions = rx_model.browse()` (same with lines)

2016-12-27 01:37 UTC, lasley commented on sale_medical_prescription/models/sale_order.py
> +                prescription_line_ids.append(line_id.id)
`prescription_lines += line`

2016-12-27 01:37 UTC, lasley commented on sale_medical_prescription/models/sale_order.py
> +            rec_id.prescription_order_ids = rx_model.browse(
`rec_id.prescription_order_ids = prescriptions`

2016-12-27 01:37 UTC, lasley commented on sale_medical_prescription/wizards/medical_sale_line_temp.py
> +            # taxes = self.env['account.tax'].compute_all()
Remove this line

2016-12-27 01:37 UTC, lasley commented on sale_medical_prescription/wizards/medical_sale_wizard.py
> +    # is empty in both cases, causing issues.
Move to roadmap

2016-12-27 21:48 UTC, tedsalmon requested changes
Minor changes requested.

2016-12-27 21:48 UTC, t3ddftw commented on sale_medical_prescription/wizards/medical_sale_temp.py
> +from openerp import models, fields, api
Imports should be sorted alphabetically.

2016-12-27 21:48 UTC, t3ddftw commented on sale_medical_prescription/wizards/medical_sale_temp.py
> +            # curr = self.pricelist_id.currency_id
Remove commented line. s/rec_id/record

2016-12-27 21:48 UTC, t3ddftw commented on sale_medical_prescription/wizards/medical_sale_temp.py
> +                # taxes += line.amount_tax
Remove commented line

2016-12-27 21:48 UTC, t3ddftw commented on sale_medical_prescription/wizards/medical_sale_temp.py
> +            # taxes = 0.0
Remove commented line

2016-12-27 21:48 UTC, t3ddftw commented on sale_medical_prescription/wizards/medical_sale_temp.py
>          #   @TODO: allow this workflow without a parent wizard
Move to README

2016-12-27 21:48 UTC, t3ddftw commented on sale_medical_prescription/wizards/medical_sale_temp.py
> +            # 'fiscal_position': self.fiscal_position.id,
Remove commented code. Move relevant `@TODO` to README

2016-12-28 01:55 UTC, lasley commented on sale_medical_prescription/__openerp__.py
> +    "version": "9.0.0.1.0",
9.0.1.0.0

2016-12-28 15:27 UTC, bmw95 commented on sale_medical_prescription/demo/sale_order_demo.xml
> +        <field name="partner_id" ref="portal.demo_user0_res_partner" />
[Travis Build Fail](https://travis-ci.org/OCA/vertical-medical/jobs/187223678#L1196)
`"External ID not found in the system: portal.demo_user0_res_partner" while parsing /home/travis/build/OCA/vertical-medical/sale_medical_prescription/demo/sale_order_demo.xml:7`

2016-12-29 04:21 UTC, bmw95 commented on sale_medical_prescription/models/sale_order.py
> +            rec_id.prescription_order_ids = rx_model.browse(
@lasley should I do `rec_id.prescription_order_ids = set(prescriptions)`? Wondering if there's a possibility of duplicates.

2016-12-29 04:26 UTC, bmw95 commented on sale_medical_prescription/wizards/medical_sale_temp.py
> +from openerp import models, fields, api
Nice catch, thought I got all of them lol.

2016-12-29 08:19 UTC, bmw95 commented
## Updated.
I'm not sure if this is an issue or not but discovered if I add multiple sale order lines in the wizard I get this error. Seems that uom is not being carried over? Not sure.
* Order lines are divided by patient
* Issue was replicated in laslabs/release/9.0
* Fixed for now at least, by disabling adding any more items (pic below is with adding items enabled)
  * If adding items is disabled, the only item can be changed to a different one and no errors happen
  * Other items can be added to the sale order in the sale order view form after redirected there when wizard is done.

![sale](https://cloud.githubusercontent.com/assets/11901801/21539322/b628a76e-cd5a-11e6-9d64-9f35598652f3.JPG)

2016-12-30 19:31 UTC, lasley commented
@bmw95 - are you adding the lines directly into the wizard using "Add an Item", or are you checking the lines in prescription line form view then hitting Create Sale to initiate the wizard with the lines?

2016-12-31 10:04 UTC, bmw95 commented
@lasley in the rx order line form view, I clicked *action* => *Create Quote(s)*, where I was shown the temp sale form below.
![hello](https://cloud.githubusercontent.com/assets/11901801/21576752/2601e9b0-cef0-11e6-8cf7-9bae287d7d0a.JPG)

Clicked on *Generate Template(s)*, showing me the next page which is the first pic I posted. I then clicked on *Add an item*, which I added the Simvastatin product, then clicked on *Create* thus causing the error.

I tried the process again today, and the logs were showing that the 2nd product, INSERT INTO sale_order_line, null column product_uom.

2016-12-31 17:04 UTC, lasley commented
You need to remove the ability for line item creation in the wizard - you should not be able to add some random prescription from there, the process is to select the prescriptions then start the wizard. Use `options="{'no_create': True}"` in the field

2016-12-31 22:53 UTC, bmw95 commented
Okie dokes.

2017-01-09 19:34 UTC, bmw95 commented
Verified cannot add order lines to wizard. Good to go!

2017-01-09 20:13 UTC, lasley commented on sale_medical_prescription/models/sale_order.py
> +            for order_line in record.order_line:
We can make things nicer + fix the coverage drop in one swoop by removing below line and switching this to:
```
for order_line in record.order_line.filtered(lambda r: r.order_line.prescription_line_id):
```

2017-01-09 20:18 UTC, bmw95 commented on sale_medical_prescription/models/sale_order.py
> +            for order_line in record.order_line:
Oh nice. Yeah that's much better.

2017-01-10 02:56 UTC, bmw95 commented
@lasley updated

2017-01-12 21:43 UTC, lasley reviewed
LGTM thanks @bmw95 

@tedsalmon can you check that your comments were attended to & approve your review please

2017-01-12 21:55 UTC, tedsalmon approved these changes
Most excellent. 👍

2017-01-14 20:57 UTC, merged