Feature/9.0 medical patient dob
OCA/vertical-medical pull request #84
Opened 2016-02-04 18:45 UTC by jamesfoster85

This is dependent on #69 

This module appends the patient's date of birth to their name when displayed in a search field autocomplete.

2016-02-04 19:08 UTC, lasley commented
@jamesfoster85 and I reviewed this one together in a side conversation. I give a :+1:

2016-02-04 19:10 UTC, pedrobaeza commented
I will review it when the dependency is merged and this PR rebased so that it's easier to do it. Let's focus in reviewing the base modules first.

2016-02-04 19:13 UTC, lasley commented
No prob, we're doing our side-reviews just so we can meet the deadlines & just dropping the modules as PRs here for finalization after we merge into our internal release branch. I'll be applying your comments from the base module onto the others ones later today. Base should be good.

2016-10-14 21:24 UTC, bmw95 commented
Ready for review.

2016-10-14 22:34 UTC, lasley requested changes

2016-10-14 22:34 UTC, lasley commented on medical_patient_dob/README.rst
> +.. repo_id is available in https://github.com/OCA/maintainer-tools/blob/master/tools/repos_with_ids.txt
Remove these lines

2016-10-14 22:34 UTC, lasley commented on medical_patient_dob/models/medical_patient.py
> +            date = fields.Datetime.from_string(self.dob).strftime('%m/%d/%Y')
Hmmmm this isn't internationalized - Europe reverses the month and day aspects of this.

I feel like we should maybe use this instead: [convert_to_display_name](https://github.com/odoo/odoo/blob/9.0/openerp/fields.py#L1438). Pretty sure that will use the internal internationalization settings in order to display proper.

2016-10-17 08:57 UTC, bmw95 commented
Updated. 
* Tests also pass when language in the UI is set to English UK (dd/mm/yyyy) for example and when language is set to None. 
* Another test was added to account for changes in date format

2016-10-17 14:09 UTC, lasley approved these changes
Thanks @bmw95 

@t3ddftw please review

2016-10-17 15:18 UTC, tedsalmon approved these changes
👍 - Looks good!

2016-10-25 16:07 UTC, merged