Feature/9.0 medical physician
OCA/vertical-medical pull request #86
Opened 2016-02-10 09:14 UTC by kenwmak

This is dependent on #69

2016-02-10 18:33 UTC, lasley commented on medical_physician/__openerp__.py
> +    'version': '9.0.1.1.0',
9.0.1.0.0

2016-02-10 18:35 UTC, lasley commented on medical_physician/models/medical_physician.py
> +    id = fields.Integer(
`id` is provided by Odoo for use as a PK. Seems that this concept is duplicating `code`, so can probably remove.

2016-02-10 18:39 UTC, lasley commented on medical_physician/models/medical_physician.py
> +            [('name', '=', 'General Practitioner')]).id,
Does this work? I don't see it declared in the data xml.

Also best to use `self.env.ref('module.id_of_record')` when getting XML objects

2016-02-10 18:47 UTC, lasley commented on medical_physician/__openerp__.py
> +##############################################################################
Use shortened OCA header

2016-02-10 18:47 UTC, lasley commented on medical_physician/models/__init__.py
> +##############################################################################
Use shortened OCA header

2016-02-10 18:47 UTC, lasley commented on medical_physician/models/medical_physician.py
> +##############################################################################
Use shortened OCA header

2016-02-10 18:47 UTC, lasley commented on medical_physician/models/medical_physician_schedule_template.py
> +##############################################################################
Use shortened OCA header

2016-02-10 18:48 UTC, lasley commented on medical_physician/models/medical_physician_service.py
> +##############################################################################
Use shortened OCA header

2016-02-10 18:49 UTC, lasley commented on medical_physician/models/medical_physician_schedule_template.py
> +        days, string='Day',
string attribute can be removed, Odoo defaults string to title case form of snake case field name.

2016-02-10 18:49 UTC, lasley commented on medical_physician/models/medical_physician_schedule_template.py
> +        minutes, string='Duration',
Remove string attr

2016-02-10 18:49 UTC, lasley commented on medical_physician/models/medical_physician.py
> +        string='Active',
Remove string attr

2016-02-10 18:50 UTC, lasley commented on medical_physician/tests/test_medical_physician.py
> +##############################################################################
Use shortened OCA header

2016-02-10 18:50 UTC, lasley commented on medical_physician/tests/test_medical_physician.py
> +        self.assertTrue(self.physician_id.partner_id.is_doctor)
Missing test for code injection if one is not defined.

2016-02-10 18:51 UTC, lasley commented on medical_physician/views/medical_menu.xml
> +    The licence is in the file __openerp__.py
@license AGPL-3

2016-02-10 18:52 UTC, lasley commented on medical_physician/views/medical_physician_view.xml
> +    The licence is in the file __openerp__.py
@license AGPL-3

2016-02-10 18:52 UTC, lasley commented on medical_physician/views/medical_specialty_view.xml
> +    The licence is in the file __openerp__.py
@license AGPL-3

2016-02-10 18:53 UTC, lasley commented on medical_physician/wizard/medical_physician_unavailable.py
> +    def action_cancel(self, cr, uid, ids, context=None):
This can be removed. It's not being used, and has already been replaced in view for `button special="cancel"`

2016-02-10 18:53 UTC, lasley commented on medical_physician/wizard/medical_physician_unavailable.py
> +    def action_set_unavailable(self, cr, uid, ids, context=None):
@api.multi

2016-02-10 18:54 UTC, lasley commented on medical_physician/wizard/medical_physician_unavailable.py
> +        string='Start', default=fields.date.today, required=True
Always use lambda for default to allow overrides. Also, you're mixing types - need to use Datetime.now, not Date.today:

```
default=lambda s: fields.Datetime.now()
```

2016-02-10 18:54 UTC, lasley commented on medical_physician/wizard/medical_physician_unavailable.py
> +        string='End', default=fields.date.today, required=True
Always use lambda for default to allow overrides. Also, you're mixing types - need to use Datetime.now, not Date.today:

```
default=lambda s: fields.Datetime.now()
```

2016-02-10 18:55 UTC, lasley commented on medical_physician/wizard/medical_physician_unavailable.py
> +        appointment_proxy = self.pool['medical.appointment']
Use env, not pool. Check out our wiki for conversion tips

2016-02-10 18:55 UTC, lasley commented on medical_physician/wizard/medical_physician_unavailable.py
> +        this = self.browse(cr, uid, ids)[0]
old api

2016-10-14 21:24 UTC, bmw95 commented
Ready for review.

2016-10-14 21:54 UTC, woodbrettm reviewed
Missing newlines at end of files

2016-10-14 21:54 UTC, bmw95 commented on medical_physician/views/medical_specialty_view.xml
> +</odoo>
last newline missing

2016-10-14 23:05 UTC, lasley requested changes

2016-10-14 23:05 UTC, lasley commented on medical_physician/README.rst
> +.. repo_id is available in https://github.com/OCA/maintainer-tools/blob/master/tools/repos_with_ids.txt
Remove

2016-10-14 23:05 UTC, lasley commented on medical_physician/data/ir_sequence_data.xml
> +<odoo>
`<odoo noupdate="1">` & remove data tag

2016-10-14 23:05 UTC, lasley commented on medical_physician/data/medical_specialties.xml
> +    <record model="medical.specialty" id="spe1">
`id` should be declared first.

Also this ID sucks; change to `medical_specialty_gp`

2016-10-14 23:05 UTC, lasley commented on medical_physician/models/medical_physician.py
> +        size=256,
256 size is default for char, remove

2016-10-14 23:05 UTC, lasley commented on medical_physician/models/medical_physician.py
> +        default=lambda self: self.env.ref('medical_physician.spe1'),
Update to new specialty id

2016-10-14 23:05 UTC, lasley commented on medical_physician/models/medical_physician.py
> +        string='Active',
string is superflous, remove

2016-10-14 23:05 UTC, lasley commented on medical_physician/models/medical_physician.py
> +    supplier = fields.Boolean(
field is superflous, remove https://github.com/odoo/odoo/blob/24aba6014c55206fb0bf18e2239ab3167a9d3cac/odoo/addons/base/res/res_partner.py#L174

2016-10-14 23:05 UTC, lasley commented on medical_physician/models/medical_specialty.py
> +        size=256,
Already default, remove

2016-10-14 23:05 UTC, lasley commented on medical_physician/models/medical_specialty.py
> +        size=256,
Already default, remove

2016-10-17 19:59 UTC, bmw95 commented
Updated as per reviews.

2016-10-19 14:29 UTC, lasley approved these changes
Thanks @bmw95 

@t3ddftw please review

2016-10-21 14:41 UTC, lasley commented
@t3ddftw ping

2016-10-25 15:11 UTC, tedsalmon approved these changes
LGTM! 👍

2016-10-27 17:27 UTC, lasley commented
@bmw95 - Please squash your commits

2016-10-27 21:17 UTC, bmw95 commented
@lasley squashed

2016-10-31 16:46 UTC, merged